#ifndef _BSP_H
#define _BSP_H

#include "bsp_sys.h"
#include "bsp_param.h"
#include "bsp_dac.h"
#include "bsp_music.h"
#include "bsp_i2c.h"
#include "bsp_huart.h"
#include "bsp_ir.h"
#include "bsp_fs.h"
#include "bsp_spi_audio.h"
#include "bsp_uart.h"
#include "bsp_saradc.h"
#include "bsp_clk.h"
#include "bsp_rtc.h"
#include "bsp_timer.h"
#include "bsp_audio.h"
#include "bsp_eq.h"
#include "bsp_record.h"
#include "bsp_saradc.h"
#include "bsp_vbat.h"
#include "bsp_asr.h"
#include "bsp_voice.h"
#endif
